AlexxIT/WebRTC

- custom_components/webrtc/www/webrtc-camera.js
Removes extra 5px of space below video element. video elements default to display: inline causing the whitespace
Adds card overflow: hidden to support rounder corners.
> Styling Fixes

- custom_components/webrtc/www/webrtc-camera.js
allows setting video poster attribute to display a still image when stream is loading.
> Add Video Poster Support

- custom_components/webrtc/www/webrtc-camera.js
Auto resume stream when changing tabs.
Auto pause stream when less than 75% of video element is in the viewport.
Possible fix for #10
> Auto Play/Pause Stream

- custom_components/webrtc/utils.py
The latest version is not compatible with HA 2021.12.0b0 because of https://github.com/home-assistant/core/pull/59360
This PR just change the naming that was updated in core from `allow_cors` to `allow_all_cors`
Fix #175
> Update allow_cors key to allow_all_cors

- README.md
- custom_components/webrtc/www/webrtc-camera.js
> Add supports custom shortcuts

- custom_components/webrtc/www/webrtc-camera.js
I was unable to use any of the custom UI buttons on two different Android devices (primarily in the HA app, but also tested in Firefox for Android). A simple solution (but perhaps not the correct one?) is to add `touchstart` events in conjunction with the existing click events. That is what this PR does.
> Fix custom UI buttons when on a touch screen device

- custom_components/webrtc/www/webrtc-camera.js
Added a unit of measurement to the indents and Added the generation of a unique class in case of using several cards in one panels. (previously styles were overridden)
----
Добавил единицу измерения в отступы и Добавил генерацию уникального класса в случае использования нескольких карт в одной панелей. (ранее стили переопределялись)
examples:
```yaml
shortcuts:
top: 12 # default in px
left: 12
shortcuts:
top: 12px
left: 12px
shortcuts:
top: 12vh
left: 12vh
...
```
> Fix shortcuts

- custom_components/webrtc/www/webrtc-camera.js
This is a reasonably simple PR that adds the ability to have a home button for PTZ, allowing the camera to return to the original location. This is done through a `data_home` section in the configuration.
For example, using ONVIF, I set a preset and then used the following config to add the button:
```yaml
data_home:
entity_id: camera.up_driveway_mainstream
preset: '1'
move_mode: GotoPreset
```
The only thing that still remains to be done is updating the wiki to document this feature.
Here's what it looks like:
> Add a home button for PTZ

- custom_components/webrtc/www/webrtc-camera.js
This CSS definition affects `ha-card`, which is a very common component in Lovelace.
In cases where the WebRTC component is embedded in another card (for example, entities card), it forces its black background styling on the **parent** `ha-card`, which has unintended consequences.
This PR will fix that bug.
> Remove background: black from ha-card style

- custom_components/webrtc/www/webrtc-camera.js
Since https://github.com/home-assistant/core/pull/73829 was merged, HA now requires that full path including the query parameters is signed.
Prior to this commit, the parameters were not included and this resulted in the websocket setup failures due to JWT token being invalid.
This commit resolves https://github.com/AlexxIT/WebRTC/issues/318 for me, although I have not tested this on any older HA instances as I don't have access to any.
> MSE: fix sign_path call for compatiblity with 2022.7

- custom_components/webrtc/www/webrtc-camera.js
Some of us plebs only have cameras (e.g. Reolink RLC-842A) with Zoom, but no Pan/Tilt functionality. Showing the PT controls always is not useful to us.
> optionally render ptz-move for users with cameras that have Z but no PT

- custom_components/webrtc/www/webrtc-camera.js
All blocks have initial border radius, but video show without border-radius.
This commit added default border radius.
Before:
After:
> Add default border-radius to video

- custom_components/webrtc/__init__.py
asyncio.wait() now forbids coroutine parameters. Only tasks are allowed.
https://docs.python.org/3/library/asyncio-task.html#asyncio.wait
> Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden.
> Fix compatibility with python 3.11

- README.md
Subject says it all.
Fixes #260
> Explain how to use in yaml mode

- custom_components/webrtc/www/webrtc-camera.js
Camera apps typically treat ptz controls slightly different than this card: **movement starts on mouse down and ends on mouse up**
This PR allows for callbacks for each event independently, enabling this behaviour.
It also adds support for long press, which is useful to set the home preset.
Usage example:
```yaml
type: custom:webrtc-camera
url: camarablanca_dvrip
shortcuts:
services:
- name: Sync
icon: mdi:clock-check
service: icsee_ptz.synchronize_clock
service_data:
camera: garden
ptz:
service: icsee_ptz.move
data_home:
camera: garden
cmd: GotoPreset
preset: 0
data_long_home:
camera: garden
cmd: SetPreset
preset: 0
data_start_left:
camera: garden
cmd: DirectionLeft
move_time: 10
data_end_left:
camera: garden
cmd: DirectionLeft
move_time: 0
data_start_right:
camera: garden
cmd: …
```
> Add support for mouse down/up/long-click to ptz UI

- README.md
- custom_components/webrtc/www/webrtc-camera.js
When clicked it downloads a screenshot
Button can be removed via config. Let me know if you prefer it to be removed by default.
Closes #524
> Add screenshot button

- custom_components/webrtc/www/digital-ptz.js
- custom_components/webrtc/www/webrtc-camera.js
Solves incompatibility with rotated video.
Reported in:
* https://github.com/AlexxIT/WebRTC/issues/21#issuecomment-1631418967
* https://github.com/dbuezas/pan-zoom-controller/issues/1
> Add video wrapper for ptz transforms for compatibility with rotations

- README.md
- custom_components/webrtc/www/webrtc-camera.js
Adds a new button to the video element, allows feed to be shown always on top, outside the browser.
Tested working on iOS 17.0.3 (latest safari), macOS (latest safari and chrome) and Ubuntu (latest chrome)
> Add picture-in-picture button

- custom_components/webrtc/www/webrtc-camera.js
Fullscreen button was not showing on iOS since it does not support the `webkitRequestFullscreen` API.
However, we can still support full screen using `video.webkitEnterFullscreen`.
Using this API has the drawback of **not showing the custom UI overlay**, just the fullscreen video with the standard controls.
In my opinion, it is still a good option to be able to go fullscreen on iOS.
Fixes https://github.com/AlexxIT/WebRTC/issues/300.
> Adds fullscreen UI button for iOS

- custom_components/webrtc/utils.py
Following previous commit, bumping bundled go2rtc version to latest
Example: https://github.com/AlexxIT/WebRTC/commit/c8ea6572636ae57d94cbf8fa4d27804c3f25d1ec
> Update go2rtc version to 1.8.4

- custom_components/webrtc/__init__.py
New functionality to support image based posters
> feat: add image entity support for poster

- custom_components/webrtc/utils.py
This PR restore dash_cast functionality ith Chromecast devices and HA 2024.3.0 and fixes #664
> Fix "takes 2 positional arguments but 3 were given"

- custom_components/webrtc/__init__.py
- hacs.json
Fixes #722 
~~Needs HA 2024.7+ (but the warning is only shown on 2024.7+ as well)~~
Tested locally, works fine
> Fix static path config for HA 2024.7+

- custom_components/webrtc/utils.py
Following previous commit, bumping bundled go2rtc version to latest
https://github.com/AlexxIT/WebRTC/issues/788
> Update go2rtc version to 1.9.8

- custom_components/webrtc/www/video-rtc.js
- custom_components/webrtc/www/webrtc-camera.js
https://github.com/AlexxIT/WebRTC/pull/811#issuecomment-2718520255
> Update go2rtc video-rtc.js to 1.9.9

- custom_components/webrtc/www/digital-ptz.js
On iOS Safari, the `<video>` element often reports `videoWidth`/`videoHeight` as `0` when only `loadedmetadata` has fired. This causes `DigitalPTZ.updateRects()` to bail early, leaving `this.videoRect` unset and breaking pinch-to-zoom until a later navigation or redraw.
This PR adds an additional listener for the `loadeddata` event, which reliably fires once the first frame is available and dimensions are known. With this change, `this.videoRect` is correctly initialized on iOS and pinch-to-zoom works immediately.
---
* Add `videoEl.addEventListener("loadeddata", this.recomputeRects);` in `DigitalPTZ` constructor
* Ensures `this.videoRect` is set when the video dimensions are first available on iOS
> Fix iOS pinch-to-zoom initialization by listening to loadeddata event
